# Web Scraping Assignment with Beautiful Soup, Selenium and Exception Handling concepts

In [1]:
import warnings
warnings.simplefilter("ignore")
warnings.filterwarnings("ignore")
import requests
from bs4 import BeautifulSoup
import selenium
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException, ElementClickInterceptedException


Importing all the necessary dependencies here.

Scrape the details of most viewed videos on YouTube from Wikipedia: Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/

You need to find following details:

A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [2]:

url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()
driver.find_element_by_xpath("//b").click()
records = []
for row in driver.find_elements_by_xpath("(//table[@class='wikitable sortable jquery-tablesorter'])[1]//tr")[1:-1]:
    temp = ''
    for element in row.find_elements_by_xpath(".//td"):        
        temp += element.text + '|'
    records.append(temp.split('|')[:-2])

df = pd.DataFrame(records, columns=['Rank', 'Video_Name', 'Artist_Name', 'Views_in_Billions', 'Upload_Date'])

arranged_cols = ['Rank', 'Video_Name', 'Artist_Name', 'Upload_Date', 'Views_in_Billions']

df.Video_Name = df.Video_Name.apply(lambda x:x[:-4].strip('"'))
df = df[arranged_cols]
df

Legality Response number from our URL is: <Response [200]>

,Rank,Video_Name,Artist_Name,Upload_Date,Views_in_Billions
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",9.58
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.61
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",5.85
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.51
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.31
5,6.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",4.60
6,7.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.53
7,8.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.47
8,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.34
9,10.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.27
10,11.,Gangnam Style,Psy,"July 15, 2012",4.24
11,12.,Dame Tu Cosita,El Chombo,"April 5, 2018",3.67
12,13.,Sugar,Maroon 5,"January 14, 2015",3.58
13,14.,Sorry,Justin Bieber,"October 22, 2015",3.48
14,15.,Roar,Katy Perry,"September 5, 2013",3.46
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.43
16,17.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.35
17,18.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",3.33
18,19.,Faded,Alan Walker,"December 3, 2015",3.17
19,20.,Dark Horse,Katy Perry,"February 20, 2014",3.17
20,21.,Girls Like You,Maroon 5,"May 31, 2018",3.16
21,22.,Lean On,Major Lazer,"March 22, 2015",3.12
22,23.,Bailando,Enrique Iglesias,"April 11, 2014",3.12
23,24.,Shake It Off,Taylor Swift,"August 18, 2014",3.11
24,25.,Let Her Go,Passenger,"July 25, 2012",3.11
25,26.,Axel F,Crazy Frog,"June 16, 2009",3.08
26,27.,Perfect,Ed Sheeran,"November 9, 2017",3.00
27,28.,Mi Gente,J Balvin,"June 29, 2017",3.00
28,29.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",2.98
29,30.,Hello,Adele,"October 22, 2015",2.90

# q2 Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.

You need to find following details:

A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [3]:
url = "https://www.bcci.tv/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

btn=driver.find_element_by_xpath("//div[@class = 'navigation__drop-down drop-down drop-down--reveal-on-hover']/div/ul/li/a")
driver.get(btn.get_attribute("href"))
time.sleep(3)

# Empty lists
match_title=[]
series=[]
place=[]
date=[]
matchtime=[]
datetime=[]

for i in driver.find_elements_by_xpath("//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__format']"):
    match_title.append(i.text)
    
for i in driver.find_elements_by_xpath("//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__tournament-label u-truncated']"):
    series.append(i.text)

for i in driver.find_elements_by_xpath("//div[@class='fixture__description u-unskewed-text']/p/span"):
    place.append(i.text)
    
for i in driver.find_elements_by_xpath("//div[@class='fixture__datetime desktop-only']"):
    datetime.append(i.text.replace('\n',' '))
    
date=[i.split(' ',3)[:3] for i in datetime]
date=[' '.join(i) for i in date]
matchtime=[i.split(' ',3)[-1] for i in datetime]

# Creating data frame
matches_data=pd.DataFrame({'Match Title': match_title,
                          "Series": series,
                          "Place": place,
                          "Date": date,
                          "Time": matchtime})
matches_data

Legality Response number from our URL is: <Response [200]>

,Match Title,Series,Place,Date,Time
0,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",Monday 08 NOVEMBER,19:30 IST
1,T20I,INDIA V NEW ZEALAND 2021,"Sawai Mansingh Stadium, Jaipur",Wednesday 17 NOVEMBER,NOVEMBER
2,T20I,INDIA V NEW ZEALAND 2021,"JSCA International Stadium Complex, Ranchi",Friday 19 NOVEMBER,NOVEMBER
3,T20I,INDIA V NEW ZEALAND 2021,"Eden Gardens, Kolkata",Sunday 21 NOVEMBER,NOVEMBER
4,TEST,INDIA V NEW ZEALAND 2021,"Green Park, Kanpur",Thursday 25 NOVEMBER,NOVEMBER
5,TEST,INDIA V NEW ZEALAND 2021,"Wankhede Stadium, Mumbai",Friday 03 DECEMBER,DECEMBER
6,ODI,INDIA V WEST INDIES 2022,"Narendra Modi Stadium, Ahmedabad",Sunday 06 FEBRUARY,FEBRUARY
7,ODI,INDIA V WEST INDIES 2022,"Sawai Mansingh Stadium, Jaipur",Wednesday 09 FEBRUARY,FEBRUARY
8,ODI,INDIA V WEST INDIES 2022,"Eden Gardens, Kolkata",Saturday 12 FEBRUARY,FEBRUARY
9,T20I,INDIA V WEST INDIES 2022,"Barabati Stadium, Cuttack",Tuesday 15 FEBRUARY,FEBRUARY

Q3 Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/

You need to find following details:

A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [4]:
url = "https://www.guru99.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

error = driver.find_element_by_xpath('//*[@id="java_technologies"]/li[3]/a').get_attribute('href')
driver.get(error)
time.sleep(3)
exception = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a').get_attribute('href')
driver.get(exception)

Data = []
table = driver.find_elements_by_xpath("//table[@class='table table-striped']//td")
for i in table:
    try:
        Data.append(i.text)
    except NoSuchElementException:
        Data.append('-')

Name = []
for i in range(2,len(Data),2):
    Name.append(Data[i])

Description = []
for i in range(3,len(Data),2):
    Description.append(Data[i])
df=pd.DataFrame({"Exception name": Name, "Exception description": Description})
df

Legality Response number from our URL is: <Response [200]>

,Exception name,Exception description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

Q4 Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/

You have to find following details:

A) Rank
B) State
C) GSDP at current price (19-20)
D) GSDP at current price (18-19)
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [9]:
url = "http://statisticstimes.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

economy = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/button')
economy.click()
time.sleep(2)
india = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
india.click()
time.sleep(2)

Legality Response number from our URL is: <Response [200]>

In [10]:
ind_eco = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
ind_eco.click()
time.sleep(2)

# Empty lists
Rank = []
State = []
GSDP1 = []
GSDP2  = []
Share = []
GDP_billion = []

try: # Scraping Rank
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException as e:
    print("No such element present")
    
try: # Scraping Name
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException as e:
    print("No such element present")
    
try: # Scraping GSDP1
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[3]"):
        GSDP1.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping GSDP2
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException as e:
    print("-")

try: # Scraping share
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException as e:
    print("-")    
    
try: # Scraping GDP billion
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDP_billion.append(i.text)
except NoSuchElementException as e:
    print("-")
    
# Creating data frame 
stats = pd.DataFrame({"Rank":Rank, "State":State, "GSDP (Cr INR at Current prices) (19-20)":GSDP1,
                      "GSDP (Cr INR at Current prices) (18-19)":GSDP2, "Share (18-19)":Share, 
                      "GDP ($ billion)":GDP_billion})
stats

,Rank,State,GSDP (Cr INR at Current prices) (19-20),GSDP (Cr INR at Current prices) (18-19),Share (18-19),GDP ($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
...,...,...,...,...,...,...
61,29,Sikkim,"28,391","25,141",0.15%,"17,060"
62,30,Nagaland,-,"24,534",0.15%,-
63,31,Arunachal Pradesh,-,"22,488",0.13%,-
64,32,Mizoram,"24,424","20,947",0.13%,"17,797"
65,33,Andaman & Nicobar Islands,-,-,-,-

Q5 Scrape the details of trending repositories on Github.com. Url = https://github.com/

You have to find the following details:

A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

Q6 Scrape the details of top 100 songs on billboard.com. Url = https://www.billboard.com/

You have to find the following details:

A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [30]:
url = "https://www.billboard.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

hot_100 = driver.find_element_by_xpath('//*[@id="root"]/div[2]/div[2]/nav/ul/li[3]/a')
hot_100.click()
time.sleep(2)

Song_name=[i.text for i in driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[@class='chart-element__information__song text--truncate color--primary']")]

Artist_name=[i.text for i in driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[@class='chart-element__information__artist text--truncate color--secondary']")]

Last_week_rank=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--last']")]

Peak_rank=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--peak']")]

Weeks_on_board=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--week']")]

# Creating data frame
Songs=pd.DataFrame({"SONG NAME":Song_name, "ARTIST":Artist_name, "LAST WEEK RANK":Last_week_rank,
                    "PEAK RANK":Peak_rank, "WEEK ON BORD":Weeks_on_board})
Songs

Legality Response number from our URL is: <Response [200]>

,SONG NAME,ARTIST,LAST WEEK RANK,PEAK RANK,WEEK ON BORD
0,Certified Lover Boy,Drake,2,1,8
1,Dangerous: The Double Album,Morgan Wallen,8,1,42
2,Planet Her,Doja Cat,7,2,18
3,"Sincerely, Kentrell",YoungBoy Never Broke Again,6,1,5
4,Sour,Olivia Rodrigo,9,1,23
...,...,...,...,...,...
195,High Off Life,Future,197,1,76
196,My Beautiful Dark Twisted Fantasy,Kanye West,199,1,157
197,To Hell With It,PinkPantheress,73,73,2
198,Cry Baby,Melanie Martinez,-,6,136
199,Born Sinner,J. Cole,191,1,117

Q7 Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/

You have to find the following details:

A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [31]:
url = "https://www.naukri.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

rec = driver.find_element_by_xpath('/html/body/div[1]/div[1]/div/ul[1]/li[2]/a/div').click()
driver.switch_to_window(driver.window_handles[1]) # switching window to make the main window as primary
search = driver.find_element_by_xpath("//div[@class='inpWrap']/input")
search.send_keys('Data Science')
search_btn = driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()

name = []
designation = []
company = []
skills = []
location = []

# fetching Names
for i in driver.find_elements_by_xpath("//span[@class='fl ellipsis']"):
    name.append(i.text)
    
# fetching Designation
for i in driver.find_elements_by_xpath("//span[@class='ellipsis clr']"):
    designation.append(i.text)

# fetching Company names
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/a[2]"):
    company.append(i.text)
    
# fetching  Skills
for i in driver.find_elements_by_xpath("//div[@class='hireSec highlightable']"):
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        skills.append(i.text)
    except NoSuchElementException:
        skills.append('-')
                
# fetching Locations
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]//span"):
    location.append(i.text)
    
# Creating a dataframe
data = list(zip(name, designation, company, skills, location))
df = pd.DataFrame(data, columns = ["Name", "Designation", "Company Name", "Skills they hire for", "Location"])
df

Legality Response number from our URL is: <Response [200]>

,Name,Designation,Company Name,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,MARSIAN Technologies LLP
7,Narasimha,Company Recruiter,Step Next Private Limited,"Data Modeling, Data Wrangling, seaborn, eda, p...",Company HR
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Pune
9,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Anik Agrawal
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Company Recruiter
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Ahmedabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",subhas patel
13,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Founder CEO
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",UK - (london)
15,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Abhishek - Only Analytics Hiring - India and
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Recruitment Lead Consultant
17,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Vadodara / Baroda
18,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Institute for Financial Management and Resear
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Programme Manager
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Chennai
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Narasimha
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Company Recruiter
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Hyderabad / Secunderabad
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Balu Ramesh
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",HR Administrator
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Trivandrum
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Asif Lucknowi
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Director
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Indore
30,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",InstaFinancials
31,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Human Resource
32,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
33,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Priyanka Akiri
34,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",HR Manager
35,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Hyderabad
36,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Kalpana Dumpala
37,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Executive Hiring
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Hyderabad / Secunderabad
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Mubarak
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Company HR
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
42,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Kushal Rastogi
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Company HR
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Mumbai
45,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Ruchi Dhote
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Senior Executive Talent Acquisition
47,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Pune
48,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Kapil Devang
49,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",HR Manager

Q8 Scrape the details of Highest selling novels. Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/

You have to find the following details:

A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [32]:
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

Book_name = []
Author_name = []
Volume_sold = []
Publisher = []
Genre = []

try: # Scraping Book name
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[2]"):
        Book_name.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Author name
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[3]"):
        Author_name.append(i.text)
except NoSuchElementException as e:
    print("-")
        
try: # Scraping Volume sold
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[4]"):
        Volume_sold.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Publisher
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[5]"):
        Publisher.append(i.text)
except NoSuchElementException as e:
    print("-") 
    
try: # Scraping Genre
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[6]"):
        Genre.append(i.text)
except NoSuchElementException as e:
    print("-")
    
# Creating data frame 
Books=pd.DataFrame({'Book Name': Book_name, 'Author Name': Author_name, 'Volume Sold': Volume_sold,
                    'Publisher': Publisher, 'Genre' : Genre})
Books

Legality Response number from our URL is: <Response [200]>

,Book Name,Author Name,Volume Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

Q9 
Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/

You have to find the following details:

A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [34]:

url = "https://www.imdb.com/list/ls095964455/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

name = []
year = []
genre = []
runtime = []
rating = []
vote = []

try: # Scraping Name
    for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
        name.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Year span
    for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
        year.append(i.text)
except NoSuchElementException as e:
    print("-")
        
try: # Scraping Genre
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p/span[5]"):
        genre.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Run time
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p/span[3]"):
        runtime.append(i.text)
except NoSuchElementException as e:
    print("-") 
    
try: # Scraping Ratings
    for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]"):
        rating.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping votes
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[4]/span[2]"):
        vote.append(i.text)
except NoSuchElementException as e:
    print("-")

# Creating a dataframe 
imdb=pd.DataFrame({'Name':name, 'Year Span':year, 'Genre':genre, 'Run Time':runtime, 'Ratings':rating, 'Votes':vote})
imdb

Legality Response number from our URL is: <Response [200]>

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,894,702"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"926,006"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"910,284"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"272,394"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"232,795"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"46,264"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"57,105"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"179,271"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"37,541"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"210,731"

Q10 Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/

You have to find the following details:

A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the Show All Dataset page through code.

In [37]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

#clicking show all datasets link
show=driver.find_element_by_xpath("//a[@href='datasets.php']")
show.click()
time.sleep(1)


#scraping dataset names
name=[]
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)

#scraping data type
data_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in info[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")
time.sleep(2)


#scraping dataset names
default_task=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")
time.sleep(2)


#scraping dataset names
attr_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in info[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")
time.sleep(2)


#scraping dataset names
no_of_instances=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")
time.sleep(2)


#scraping dataset names
no_of_attributes=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")
time.sleep(2)


#scraping dataset names
year=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in info[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Name':name,
                'Data_type':data_type,
                'Task':default_task,
                'Attribute_type':attr_type,
                'No_of_instances':no_of_instances,
                'No_of_attributes':no_of_attributes,
                'Year':year})

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021

In [42]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

#clicking show all datasets link
show=driver.find_element_by_xpath("//a[@href='datasets.php']")
show.click()
time.sleep(1)


#scraping dataset names
name=[]
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)

#scraping data type
data_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in info[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")
time.sleep(2)


#scraping dataset names
default_task=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")
time.sleep(2)


#scraping dataset names
attr_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in info[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")
time.sleep(2)


#scraping dataset names
no_of_instances=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")
time.sleep(2)


#scraping dataset names
no_of_attributes=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")
time.sleep(2)


#scraping dataset names
year=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in info[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Name':name,
                'Data_type':data_type,
                'Task':default_task,
                'Attribute_type':attr_type,
                'No_of_instances':no_of_instances,
                'No_of_attributes':no_of_attributes,
                'Year':year})
df

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021

Q5. Q5. Scrape the details of trending repositories on Github.com. Url = https://github.com/ You have to find the following details: A) Repository title B) Repository description C) Contributors count D) Language used Note: - From the home page you have to click on the trending option from Explore menu through code.

In [44]:
driver= webdriver.Chrome('chromedriver.exe')
driver.get('https://github.com/trending')

In [45]:
all_box_url = driver.find_elements_by_xpath('//article/h1/a')

In [46]:
all_urls = []
for one_url in all_box_url:
    all_urls.append(one_url.get_attribute('href'))

In [47]:
all_urls

['https://github.com/microsoft/ML-For-Beginners',
 'https://github.com/ruanyf/weekly',
 'https://github.com/DrKLO/Telegram',
 'https://github.com/vandadnp/flutter-tips-and-tricks',
 'https://github.com/d2l-ai/d2l-zh',
 'https://github.com/ibraheemdev/modern-unix',
 'https://github.com/foxsen/archbase',
 'https://github.com/TandoorRecipes/recipes',
 'https://github.com/knownsec/KCon',
 'https://github.com/insitro/redun',
 'https://github.com/CesiumGS/cesium',
 'https://github.com/github/gitignore',
 'https://github.com/WordPress/wordpress-develop',
 'https://github.com/FaridSafi/react-native-gifted-chat',
 'https://github.com/Kholid060/automa',
 'https://github.com/google/re2',
 'https://github.com/facebook/react-native',
 'https://github.com/ossu/computer-science',
 'https://github.com/alibaba/ice',
 'https://github.com/helix-editor/helix',
 'https://github.com/fmtlib/fmt',
 'https://github.com/alibaba/easyexcel',
 'https://github.com/nnjeim/world',
 'https://github.com/bombomby/optick',
 'https://github.com/Roblox/luau']

In [49]:
all_data = []
for one_url in all_urls:
    
    driver.get(one_url)
    languages_used_elemens = driver.find_elements_by_xpath('//a[contains(@data-ga-click,"Repository, language")]')
    
    language_used = []
    for lang in languages_used_elemens:
        language_used.append(lang.text.split('\n')[0])
    all_data.append({
        'language_used': ', '.join(language_used),
    })

In [50]:
all_data

[{'language_used': 'Jupyter Notebook'},
 {'language_used': ''},
 {'language_used': 'Java, C++, C, Assembly, Perl, Go'},
 {'language_used': 'Dart'},
 {'language_used': 'Python, HTML, TeX, Shell'},
 {'language_used': ''},
 {'language_used': 'TeX, C, Assembly, Makefile, Dockerfile, CSS'},
 {'language_used': 'HTML, JavaScript, Python, TypeScript, Vue, CSS'},
 {'language_used': 'JavaScript, HTML'},
 {'language_used': 'Python'},
 {'language_used': 'JavaScript, HTML, GLSL'},
 {'language_used': ''},
 {'language_used': 'PHP, CSS, JavaScript, SCSS, HTML, XSLT'},
 {'language_used': 'TypeScript, JavaScript'},
 {'language_used': 'Vue, JavaScript, CSS, HTML'},
 {'language_used': 'C++, Python, Makefile, Starlark, Perl, CMake'},
 {'language_used': 'JavaScript, Java, C++, Objective-C, Objective-C++, Starlark'},
 {'language_used': ''},
 {'language_used': 'TypeScript, JavaScript, EJS, CSS, Rust'},
 {'language_used': 'Rust, Scheme, JavaScript, CSS, Handlebars, Nix'},
 {'language_used': 'C++, Python, CMake, Shell, Cuda, Starlark'},
 {'language_used': 'Java'},
 {'language_used': 'PHP'},
 {'language_used': 'C#, C++, C, Lua, Batchfile, CMake, HLSL'},
 {'language_used': 'C++, Lua, C, Python, TeX, CMake'}]

In [52]:
button = driver.find_element_by_xpath("//ul[@class = 'd-lg-flex list-style-none']/li[4]/details/summary")
button.click()

button2= driver.find_element_by_xpath("//ul[@class = 'list-style-none mb-3'][2]/li[3]/a")
button2.click()
time.sleep(1)

In [53]:
URLs = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']/a")

URL_List = []

for i in URLs:
    URL_List.append(i.get_attribute('href'))
    
URL_List

['https://github.com/microsoft/ML-For-Beginners',
 'https://github.com/ruanyf/weekly',
 'https://github.com/DrKLO/Telegram',
 'https://github.com/vandadnp/flutter-tips-and-tricks',
 'https://github.com/d2l-ai/d2l-zh',
 'https://github.com/ibraheemdev/modern-unix',
 'https://github.com/foxsen/archbase',
 'https://github.com/TandoorRecipes/recipes',
 'https://github.com/knownsec/KCon',
 'https://github.com/insitro/redun',
 'https://github.com/CesiumGS/cesium',
 'https://github.com/github/gitignore',
 'https://github.com/WordPress/wordpress-develop',
 'https://github.com/FaridSafi/react-native-gifted-chat',
 'https://github.com/Kholid060/automa',
 'https://github.com/google/re2',
 'https://github.com/facebook/react-native',
 'https://github.com/ossu/computer-science',
 'https://github.com/alibaba/ice',
 'https://github.com/helix-editor/helix',
 'https://github.com/fmtlib/fmt',
 'https://github.com/alibaba/easyexcel',
 'https://github.com/nnjeim/world',
 'https://github.com/bombomby/optick',
 'https://github.com/Roblox/luau']

In [54]:
Repository_Name = []

for i in URL_List:
    driver.get(i)
    url=driver.find_elements_by_xpath("//strong[@class='mr-2 flex-self-stretch']/a")
    for i in url: 
        Repository_Name.append(i.text)
        
Repository_Name

['ML-For-Beginners',
 'weekly',
 'Telegram',
 'flutter-tips-and-tricks',
 'd2l-zh',
 'modern-unix',
 'archbase',
 'recipes',
 'KCon',
 'redun',
 'cesium',
 'gitignore',
 'wordpress-develop',
 'react-native-gifted-chat',
 'automa',
 're2',
 'react-native',
 'computer-science',
 'ice',
 'helix',
 'fmt',
 'easyexcel',
 'world',
 'optick',
 'luau']

In [55]:
Repository_Description = []



for i in URL_List:
    driver.get(i)
    try:
        P=driver.find_element_by_xpath("//div[@class='BorderGrid-cell']/p")
        Repository_Description.append(P.text)
    except NoSuchElementException:
        Repository_Description.append("Description Not available")
        
Repository_Description

['12 weeks, 26 lessons, 52 quizzes, classic Machine Learning for all',
 '科技爱好者周刊，每周五发布',
 'Telegram for Android source',
 'A Collection of Flutter and Dart Tips and Tricks',
 '《动手学深度学习》：面向中文读者、能运行、可讨论。中英文版被全球200所大学采用教学。',
 'A collection of modern/faster/saner alternatives to common unix commands.',
 '教科书《计算机体系结构基础》（胡伟武等，第三版）的开源版本',
 'Application for managing recipes, planning meals, building shopping lists and much much more!',
 'KCon is a famous Hacker Con powered by Knownsec Team.',
 'Yet another redundant workflow engine',
 'An open-source JavaScript library for world-class 3D globes and maps 🌎',
 'A collection of useful .gitignore templates',
 'WordPress Develop, Git-ified. Synced from git://develop.git.wordpress.org/, including branches and tags! This repository is just a mirror of the WordPress subversion repository. Please include a link to a pre-existing ticket on https://core.trac.wordpress.org/ with every pull request.',
 '💬 The most complete chat UI for React Native',
 'A chrome extension for automating your browser by connecting blocks',
 'RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression engines like those used in PCRE, Perl, and Python. It is a C++ library.',
 'A framework for building native applications using React',
 '🎓 Path to a free self-taught education in Computer Science!',
 '🚀 The Progressive Framework Based On React（基于 React 的渐进式研发框架）',
 'A post-modern modal text editor.',
 'A modern formatting library',
 '快速、简单避免OOM的java处理Excel工具',
 'A Laravel package providing a list of the countries, states, cities, currencies and timezones',
 'C++ Profiler For Games',
 'A fast, small, safe, gradually typed embeddable scripting language derived from Lua']

In [56]:
len(Repository_Name)

25

In [57]:
Contributors = []

for i in URL_List:
    driver.get(i)
    try:
        P=driver.find_element_by_xpath("//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contributors.append(P.text)
    except:
        Contributors.append('NA')
Contributors

['96',
 '26',
 '16',
 'NA',
 '179',
 '10',
 'NA',
 '63',
 '4',
 '5',
 '244',
 '1,272',
 '71',
 '169',
 '4',
 '46',
 '2,253',
 '116',
 '82',
 '89',
 '312',
 '38',
 '2',
 '13',
 '26']

In [58]:
github = pd.DataFrame({"Repository title":Repository_Name[:25],"Repository description":Repository_Description[:25],
                       "Contributors count": Contributors[:25],"Language used": all_data[:25]})
github

,Repository title,Repository description,Contributors count,Language used
0,ML-For-Beginners,"12 weeks, 26 lessons, 52 quizzes, classic Mach...",96,{'language_used': 'Jupyter Notebook'}
1,weekly,科技爱好者周刊，每周五发布,26,{'language_used': ''}
2,Telegram,Telegram for Android source,16,"{'language_used': 'Java, C++, C, Assembly, Per..."
3,flutter-tips-and-tricks,A Collection of Flutter and Dart Tips and Tricks,NA,{'language_used': 'Dart'}
4,d2l-zh,《动手学深度学习》：面向中文读者、能运行、可讨论。中英文版被全球200所大学采用教学。,179,"{'language_used': 'Python, HTML, TeX, Shell'}"
5,modern-unix,A collection of modern/faster/saner alternativ...,10,{'language_used': ''}
6,archbase,教科书《计算机体系结构基础》（胡伟武等，第三版）的开源版本,NA,"{'language_used': 'TeX, C, Assembly, Makefile,..."
7,recipes,"Application for managing recipes, planning mea...",63,"{'language_used': 'HTML, JavaScript, Python, T..."
8,KCon,KCon is a famous Hacker Con powered by Knownse...,4,"{'language_used': 'JavaScript, HTML'}"
9,redun,Yet another redundant workflow engine,5,{'language_used': 'Python'}
10,cesium,An open-source JavaScript library for world-cl...,244,"{'language_used': 'JavaScript, HTML, GLSL'}"
11,gitignore,A collection of useful .gitignore templates,"1,272",{'language_used': ''}
12,wordpress-develop,"WordPress Develop, Git-ified. Synced from git:...",71,"{'language_used': 'PHP, CSS, JavaScript, SCSS,..."
13,react-native-gifted-chat,💬 The most complete chat UI for React Native,169,"{'language_used': 'TypeScript, JavaScript'}"
14,automa,A chrome extension for automating your browser...,4,"{'language_used': 'Vue, JavaScript, CSS, HTML'}"
15,re2,"RE2 is a fast, safe, thread-friendly alternati...",46,"{'language_used': 'C++, Python, Makefile, Star..."
16,react-native,A framework for building native applications u...,"2,253","{'language_used': 'JavaScript, Java, C++, Obje..."
17,computer-science,🎓 Path to a free self-taught education in Comp...,116,{'language_used': ''}
18,ice,🚀 The Progressive Framework Based On React（基于 ...,82,"{'language_used': 'TypeScript, JavaScript, EJS..."
19,helix,A post-modern modal text editor.,89,"{'language_used': 'Rust, Scheme, JavaScript, C..."
20,fmt,A modern formatting library,312,"{'language_used': 'C++, Python, CMake, Shell, ..."
21,easyexcel,快速、简单避免OOM的java处理Excel工具,38,{'language_used': 'Java'}
22,world,A Laravel package providing a list of the coun...,2,{'language_used': 'PHP'}
23,optick,C++ Profiler For Games,13,"{'language_used': 'C#, C++, C, Lua, Batchfile,..."
24,luau,"A fast, small, safe, gradually typed embeddabl...",26,"{'language_used': 'C++, Lua, C, Python, TeX, C..."